# Generated by Django 3.0.14 on 2022-04-05 20:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_doctor_account_detail'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Booked',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='city_id',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='h_id',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='major_id',
        ),
        migrations.RemoveField(
            model_name='getlinks',
            name='d_id',
        ),
        migrations.RemoveField(
            model_name='getlinks',
            name='p_id',
        ),
        migrations.RemoveField(
            model_name='hospital',
            name='city_id',
        ),
        migrations.DeleteModel(
            name='Booking',
        ),
        migrations.DeleteModel(
            name='doctor',
        ),
        migrations.DeleteModel(
            name='getLinks',
        ),
        migrations.DeleteModel(
            name='hospital',
        ),
        migrations.DeleteModel(
            name='patient',
        ),
    ]
